version: '3.1'

services:

  wordpress:
    image: wordpress:6.1.0-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: 1q2w3e4r
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: