version: '3.1'
services: 
    nginx:
        image: nginx:latest
        restart: always
        ports: 
        - "80:80"
    volumes: 
        - ./config-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./cert:/etc/nginx/cert